name: 'nbctl'
description: 'convert jupyter *.ipynb file to markdown'
author: 'xiexianbin <me@xiexianbin>'
inputs:
  log:
    description: 'logger level, value [DEBUG|INFO|WARN|ERROR|FATAL]'
    default: 'DEBUG'
  script:
    description: 'script to run'
    default: 'find . -type f -name "*.ipynb" | xargs -I{} nbctl --input {} -f'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  color: 'blue'
  icon: 'chevrons-right'
